CREATE DATABASE STUDENTDB;
SELECT NAME FROM SYS.DATABASES;
USE STUDENTDB;
CREATE TABLE STUDENTS(
STUDENTID INT PRIMARY KEY,
NAME VARCHAR(50),
AGE INT, 
DEPARTMENT VARCHAR(50),
CGPA DECIMAL(3,2)
);
INSERT INTO STUDENTS VALUES 
(1,'MAIDA',22,'BI',2.9),
(2,'AIMEN',19,'SE',3.2),
(3,'ZAINAB',20,'IT',3.4),
(4,'AMNA',21,'SE',3.7),
(5,'FIZZA',18,'AI',3.0);
SELECT * FROM STUDENTS
ALTER TABLE STUDENTS 
ADD EMAIL VARCHAR(15);
SP_HELP STUDENTS;
ALTER TABLE STUDENTS
ALTER COLUMN DEPARTMENT VARCHAR(25);
SP_HELP STUDENTS;
UPDATE STUDENTS 
SET CGPA=3.6 WHERE STUDENTID=1;
DELETE FROM STUDENTS
WHERE STUDENTID=5;
SELECT * FROM STUDENTS;
ALTER TABLE STUDENTS 
DROP COLUMN EMAIL;
DROP TABLE STUDENTS;
CREATE TABLE COURSES(
COURSEID INT PRIMARY KEY,
COURSENAME VARCHAR(20) NOT NULL,
CREDITS INT
);

